### ISSUE TITLE
markdown_includes are always parsed as Markdown , even if they are HTML

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/canonicalwebteam.templatefinder#10]
In Vanilla we use `markdown_includes` to include HTML code of the examples.
Each example is just an .html file with HTML contents.

But because it's treaded as markdown and passed through markdown processor sometimes (depending on content of example HTML) additional unexpected paragraphs `<p>` are added to result HTML, sometimes causing examples to break or look different than expected.

Examples:

```html
<a href="#">Something</a>
```

Turns into:

```html
<p><a href="#">Something</a></p>
```

and:

```html
<input type="range" />
<input type="range" disabled />
```
 Turns into 

```html
<p><input type="range" /></p>
<input type="range" disabled />
```

### Expected

Markdown processor should not modify HTML or there should be an option to not parse includes as Markdown. Either have separate `html_includes` or if path of `markdown_includes` is `*.html` file, markdown processor should be skipped.

**Comment by nottrobin** [comment]
I don't think we can really work around this. We can't parse a small section inside a Markdown document as pure HTML without Markdown.

I think you'll just have to work around this problem.
