### ISSUE TITLE
Publish major version for breaking change not to expose underscore files

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/canonicalwebteam.templatefinder#16]
https://github.com/canonical-web-and-design/canonicalwebteam.templatefinder/commit/a2985946ed80d0117618c20a4d880f9dc0bf91b2

the assumption is wrong, the modal contact forms on ubuntu.com need to pull in /shared/forms/interactive/_<section> via javascript... this breaks the forms... and did.

**Comment by pmahnke** [comment]
we could leave this code and fixup ubuntu.com by renaming the modal pages as well.

**Comment by nottrobin** [comment]
We discussed this a bit further in web squad stand-up.

The pattern of sharing content with the client through underscore-named files was also used in, at least, maas.io and canonical.com (how quickly code multiplies). So it's clear that the change to not expose underscore files is a significant breaking change.

However, I think we definitely still want stop exposing underscore files. Files shared with the client are not "hidden" or "partial" files, they effectively form part of the site's API, so I think they really should not be named with underscores. Underscores are (should be) explicitly for files internal to the template system, and not directly output by the app.

So, steps:

- Delete the https://pypi.org/project/canonicalwebteam.templatefinder/0.2.5/, publish 0.3.0 instead (or maybe 1.0.0?)
- Update ubuntu.com, maas.io, canonical.com, anywhere else to change the filenames to not contain underscores

**Comment by nottrobin** [comment]
Deleted 0.2.5, and publishing 1.0.0 here: https://github.com/canonical-web-and-design/canonicalwebteam.templatefinder/pull/17

**Comment by nottrobin** [comment]
Updating canonical.com here: https://github.com/canonical-web-and-design/canonical.com/pull/230/commits/622a2df1628fc52366fc89034b4e5f525855e909

**Comment by nottrobin** [comment]
Added this PR to ubuntu.com: https://github.com/canonical-web-and-design/ubuntu.com/pull/7565
